# Generated by Django 5.0.6 on 2024-05-31 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('MaDanhMuc', models.AutoField(primary_key=True, serialize=False)),
                ('TenDanhMuc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=100)),
                ('TenBe', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDonHang', models.AutoField(primary_key=True, serialize=False)),
                ('NgayDatHang', models.DateField()),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiaChiGiaoHang', models.CharField(max_length=255)),
                ('TrangThai', models.BooleanField(default=False)),
                ('MaKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KiemTraLan2.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSanPham', models.AutoField(primary_key=True, serialize=False)),
                ('TenSanPham', models.CharField(max_length=255)),
                ('MoTa', models.TextField()),
                ('Gia', models.FloatField()),
                ('HinhAnhDaiDien', models.ImageField(upload_to='')),
                ('MaDanhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KiemTraLan2.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('MaChiTietDonHang', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField()),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MaDonHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KiemTraLan2.donhang')),
                ('MaSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KiemTraLan2.sanpham')),
            ],
        ),
    ]
